import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  // Production (Vercel) → dist. Dev → .next so build never corrupts the dev server.
  distDir: process.env.NODE_ENV === 'production' ? 'dist' : '.next',
  eslint: {
    // Lint runs separately; missing optional plugin must not block production builds
    ignoreDuringBuilds: true,
  },
  typescript: {
    ignoreBuildErrors: false,
  },
  images: {
    formats: ['image/avif', 'image/webp'],
    qualities: [75, 80, 85, 90],
    deviceSizes: [640, 750, 828, 1080, 1200, 1920],
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'anasampaio.pt',
        pathname: '/wp-content/**',
      },
    ],
  },
  async redirects() {
    return [
      // Root → default locale
      { source: '/', destination: '/pt', permanent: true },

      // Phase 2 — merge Serviços / Terapia / Resultados / Glossário into hubs
      { source: '/:locale(pt|es|en)/servicos', destination: '/:locale/tratamentos', permanent: true },
      { source: '/:locale(pt|es|en)/servicios', destination: '/:locale/tratamientos', permanent: true },
      { source: '/:locale(pt|es|en)/services', destination: '/:locale/treatments', permanent: true },
      { source: '/:locale(pt|es|en)/terapia-capilar', destination: '/:locale/tratamentos', permanent: true },
      { source: '/:locale(pt|es|en)/hair-scalp-therapy', destination: '/:locale/treatments', permanent: true },
      { source: '/:locale(pt|es|en)/resultados', destination: '/:locale/sobre', permanent: true },
      { source: '/:locale(pt|es|en)/results', destination: '/:locale/about', permanent: true },
      { source: '/:locale(pt|es|en)/glossario', destination: '/:locale/blog', permanent: true },
      { source: '/:locale(pt|es|en)/glosario', destination: '/:locale/blog', permanent: true },
      { source: '/:locale(pt|es|en)/glossary', destination: '/:locale/blog', permanent: true },

      // Legacy prototype / WP-style paths → pt locale
      { source: '/servicos', destination: '/pt/tratamentos', permanent: true },
      { source: '/tratamentos', destination: '/pt/tratamentos', permanent: true },
      { source: '/terapia-capilar', destination: '/pt/tratamentos', permanent: true },
      { source: '/sobre', destination: '/pt/sobre', permanent: true },
      { source: '/produtos', destination: '/pt/produtos', permanent: true },
      { source: '/blog', destination: '/pt/blog', permanent: true },
      { source: '/glossario', destination: '/pt/blog', permanent: true },
      { source: '/depoimentos', destination: '/pt/depoimentos', permanent: true },
      { source: '/resultados', destination: '/pt/sobre', permanent: true },
      { source: '/contacto', destination: '/pt/contacto', permanent: true },
      { source: '/agendamento', destination: '/pt/agendamento', permanent: true },
      { source: '/faq', destination: '/pt/faq', permanent: true },
      { source: '/termos-de-utilizacao', destination: '/pt/termos', permanent: true },
      { source: '/termos', destination: '/pt/termos', permanent: true },
      { source: '/politica-de-privacidade', destination: '/pt/politica-de-privacidade', permanent: true },
      { source: '/politica-de-cookies', destination: '/pt/politica-de-cookies', permanent: true },
      { source: '/livro-de-reclamacoes', destination: '/pt/livro-de-reclamacoes', permanent: true },
      { source: '/livro-de-elogios', destination: '/pt/livro-de-elogios', permanent: true },

      // WordPress blog post redirects
      { source: '/terapia-capilar-para-cabelos-oleosos', destination: '/pt/blog/terapia-capilar-para-cabelos-oleosos', permanent: true },
      { source: '/terapia-capilar-para-cabelos-oleosos/', destination: '/pt/blog/terapia-capilar-para-cabelos-oleosos', permanent: true },
      { source: '/blog/terapia-capilar-para-cabelos-oleosos', destination: '/pt/blog/terapia-capilar-para-cabelos-oleosos', permanent: true },
      { source: '/blog/terapia-capilar-para-cabelos-oleosos/', destination: '/pt/blog/terapia-capilar-para-cabelos-oleosos', permanent: true },
      { source: '/como-escolher-um-terapeuta-capilar', destination: '/pt/blog/como-escolher-um-terapeuta-capilar', permanent: true },
      { source: '/como-escolher-um-terapeuta-capilar/', destination: '/pt/blog/como-escolher-um-terapeuta-capilar', permanent: true },
      { source: '/blog/como-escolher-um-terapeuta-capilar', destination: '/pt/blog/como-escolher-um-terapeuta-capilar', permanent: true },
      { source: '/blog/como-escolher-um-terapeuta-capilar/', destination: '/pt/blog/como-escolher-um-terapeuta-capilar', permanent: true },
      { source: '/melhores-tecnicas-de-terapia-capilar', destination: '/pt/blog/melhores-tecnicas-de-terapia-capilar', permanent: true },
      { source: '/melhores-tecnicas-de-terapia-capilar/', destination: '/pt/blog/melhores-tecnicas-de-terapia-capilar', permanent: true },
      { source: '/blog/melhores-tecnicas-de-terapia-capilar', destination: '/pt/blog/melhores-tecnicas-de-terapia-capilar', permanent: true },
      { source: '/blog/melhores-tecnicas-de-terapia-capilar/', destination: '/pt/blog/melhores-tecnicas-de-terapia-capilar', permanent: true },
      { source: '/tratamento-capilar-para-cabelos-danificados', destination: '/pt/blog/tratamento-capilar-para-cabelos-danificados', permanent: true },
      { source: '/tratamento-capilar-para-cabelos-danificados/', destination: '/pt/blog/tratamento-capilar-para-cabelos-danificados', permanent: true },
      { source: '/blog/tratamento-capilar-para-cabelos-danificados', destination: '/pt/blog/tratamento-capilar-para-cabelos-danificados', permanent: true },
      { source: '/blog/tratamento-capilar-para-cabelos-danificados/', destination: '/pt/blog/tratamento-capilar-para-cabelos-danificados', permanent: true },
      { source: '/terapeuta-capilar-especializado-em-queda-de-cabelo', destination: '/pt/blog/terapeuta-capilar-especializado-em-queda-de-cabelo', permanent: true },
      { source: '/terapeuta-capilar-especializado-em-queda-de-cabelo/', destination: '/pt/blog/terapeuta-capilar-especializado-em-queda-de-cabelo', permanent: true },
      { source: '/blog/terapeuta-capilar-especializado-em-queda-de-cabelo', destination: '/pt/blog/terapeuta-capilar-especializado-em-queda-de-cabelo', permanent: true },
      { source: '/blog/terapeuta-capilar-especializado-em-queda-de-cabelo/', destination: '/pt/blog/terapeuta-capilar-especializado-em-queda-de-cabelo', permanent: true },
      { source: '/cabeleireiro-feminino-leiria-portugal', destination: '/pt/blog/cabeleireiro-feminino-leiria-portugal', permanent: true },
      { source: '/cabeleireiro-feminino-leiria-portugal/', destination: '/pt/blog/cabeleireiro-feminino-leiria-portugal', permanent: true },
      { source: '/blog/cabeleireiro-feminino-leiria-portugal', destination: '/pt/blog/cabeleireiro-feminino-leiria-portugal', permanent: true },
      { source: '/blog/cabeleireiro-feminino-leiria-portugal/', destination: '/pt/blog/cabeleireiro-feminino-leiria-portugal', permanent: true },
      { source: '/servicos-de-cabeleireiro-leiria-portugal', destination: '/pt/blog/servicos-de-cabeleireiro-leiria-portugal', permanent: true },
      { source: '/servicos-de-cabeleireiro-leiria-portugal/', destination: '/pt/blog/servicos-de-cabeleireiro-leiria-portugal', permanent: true },
      { source: '/blog/servicos-de-cabeleireiro-leiria-portugal', destination: '/pt/blog/servicos-de-cabeleireiro-leiria-portugal', permanent: true },
      { source: '/blog/servicos-de-cabeleireiro-leiria-portugal/', destination: '/pt/blog/servicos-de-cabeleireiro-leiria-portugal', permanent: true },
      { source: '/tratamento-capilar-especializado-em-marinha-grande-leiria-pt', destination: '/pt/blog/tratamento-capilar-especializado-em-marinha-grande-leiria-pt', permanent: true },
      { source: '/tratamento-capilar-especializado-em-marinha-grande-leiria-pt/', destination: '/pt/blog/tratamento-capilar-especializado-em-marinha-grande-leiria-pt', permanent: true },
      { source: '/blog/tratamento-capilar-especializado-em-marinha-grande-leiria-pt', destination: '/pt/blog/tratamento-capilar-especializado-em-marinha-grande-leiria-pt', permanent: true },
      { source: '/blog/tratamento-capilar-especializado-em-marinha-grande-leiria-pt/', destination: '/pt/blog/tratamento-capilar-especializado-em-marinha-grande-leiria-pt', permanent: true },
      { source: '/dermatite-seborreica', destination: '/pt/blog/dermatite-seborreica', permanent: true },
      { source: '/dermatite-seborreica/', destination: '/pt/blog/dermatite-seborreica', permanent: true },
      { source: '/blog/dermatite-seborreica', destination: '/pt/blog/dermatite-seborreica', permanent: true },
      { source: '/blog/dermatite-seborreica/', destination: '/pt/blog/dermatite-seborreica', permanent: true },
      { source: '/calvicie', destination: '/pt/blog/calvicie', permanent: true },
      { source: '/calvicie/', destination: '/pt/blog/calvicie', permanent: true },
      { source: '/blog/calvicie', destination: '/pt/blog/calvicie', permanent: true },
      { source: '/blog/calvicie/', destination: '/pt/blog/calvicie', permanent: true },
      { source: '/alopecia-areata', destination: '/pt/blog/alopecia-areata', permanent: true },
      { source: '/alopecia-areata/', destination: '/pt/blog/alopecia-areata', permanent: true },
      { source: '/blog/alopecia-areata', destination: '/pt/blog/alopecia-areata', permanent: true },
      { source: '/blog/alopecia-areata/', destination: '/pt/blog/alopecia-areata', permanent: true },
      { source: '/corte-bordado', destination: '/pt/blog/corte-bordado', permanent: true },
      { source: '/corte-bordado/', destination: '/pt/blog/corte-bordado', permanent: true },
      { source: '/blog/corte-bordado', destination: '/pt/blog/corte-bordado', permanent: true },
      { source: '/blog/corte-bordado/', destination: '/pt/blog/corte-bordado', permanent: true },
      { source: '/massagem-capilar-com-oleos-terapeuticos', destination: '/pt/blog/massagem-capilar-com-oleos-terapeuticos', permanent: true },
      { source: '/massagem-capilar-com-oleos-terapeuticos/', destination: '/pt/blog/massagem-capilar-com-oleos-terapeuticos', permanent: true },
      { source: '/blog/massagem-capilar-com-oleos-terapeuticos', destination: '/pt/blog/massagem-capilar-com-oleos-terapeuticos', permanent: true },
      { source: '/blog/massagem-capilar-com-oleos-terapeuticos/', destination: '/pt/blog/massagem-capilar-com-oleos-terapeuticos', permanent: true },
      { source: '/cha-terapia-capilar', destination: '/pt/blog/cha-terapia-capilar', permanent: true },
      { source: '/cha-terapia-capilar/', destination: '/pt/blog/cha-terapia-capilar', permanent: true },
      { source: '/blog/cha-terapia-capilar', destination: '/pt/blog/cha-terapia-capilar', permanent: true },
      { source: '/blog/cha-terapia-capilar/', destination: '/pt/blog/cha-terapia-capilar', permanent: true },
      { source: '/musicaterapia', destination: '/pt/blog/musicaterapia', permanent: true },
      { source: '/musicaterapia/', destination: '/pt/blog/musicaterapia', permanent: true },
      { source: '/blog/musicaterapia', destination: '/pt/blog/musicaterapia', permanent: true },
      { source: '/blog/musicaterapia/', destination: '/pt/blog/musicaterapia', permanent: true },
      { source: '/blend-de-oleos-naturais-personalizados', destination: '/pt/blog/blend-de-oleos-naturais-personalizados', permanent: true },
      { source: '/blend-de-oleos-naturais-personalizados/', destination: '/pt/blog/blend-de-oleos-naturais-personalizados', permanent: true },
      { source: '/blog/blend-de-oleos-naturais-personalizados', destination: '/pt/blog/blend-de-oleos-naturais-personalizados', permanent: true },
      { source: '/blog/blend-de-oleos-naturais-personalizados/', destination: '/pt/blog/blend-de-oleos-naturais-personalizados', permanent: true },
      { source: '/alta-frequencia', destination: '/pt/blog/alta-frequencia', permanent: true },
      { source: '/alta-frequencia/', destination: '/pt/blog/alta-frequencia', permanent: true },
      { source: '/blog/alta-frequencia', destination: '/pt/blog/alta-frequencia', permanent: true },
      { source: '/blog/alta-frequencia/', destination: '/pt/blog/alta-frequencia', permanent: true },
      { source: '/led-vermelho', destination: '/pt/blog/led-vermelho', permanent: true },
      { source: '/led-vermelho/', destination: '/pt/blog/led-vermelho', permanent: true },
      { source: '/blog/led-vermelho', destination: '/pt/blog/led-vermelho', permanent: true },
      { source: '/blog/led-vermelho/', destination: '/pt/blog/led-vermelho', permanent: true },
      { source: '/detox-do-couro-cabeludo', destination: '/pt/blog/detox-do-couro-cabeludo', permanent: true },
      { source: '/detox-do-couro-cabeludo/', destination: '/pt/blog/detox-do-couro-cabeludo', permanent: true },
      { source: '/blog/detox-do-couro-cabeludo', destination: '/pt/blog/detox-do-couro-cabeludo', permanent: true },
      { source: '/blog/detox-do-couro-cabeludo/', destination: '/pt/blog/detox-do-couro-cabeludo', permanent: true },
      { source: '/escova-terapeutica', destination: '/pt/blog/escova-terapeutica', permanent: true },
      { source: '/escova-terapeutica/', destination: '/pt/blog/escova-terapeutica', permanent: true },
      { source: '/blog/escova-terapeutica', destination: '/pt/blog/escova-terapeutica', permanent: true },
      { source: '/blog/escova-terapeutica/', destination: '/pt/blog/escova-terapeutica', permanent: true },
      { source: '/reposicao-lipidica', destination: '/pt/blog/reposicao-lipidica', permanent: true },
      { source: '/reposicao-lipidica/', destination: '/pt/blog/reposicao-lipidica', permanent: true },
      { source: '/blog/reposicao-lipidica', destination: '/pt/blog/reposicao-lipidica', permanent: true },
      { source: '/blog/reposicao-lipidica/', destination: '/pt/blog/reposicao-lipidica', permanent: true },
      { source: '/reposicao-hidrica-no-cabelo', destination: '/pt/blog/reposicao-hidrica-no-cabelo', permanent: true },
      { source: '/reposicao-hidrica-no-cabelo/', destination: '/pt/blog/reposicao-hidrica-no-cabelo', permanent: true },
      { source: '/blog/reposicao-hidrica-no-cabelo', destination: '/pt/blog/reposicao-hidrica-no-cabelo', permanent: true },
      { source: '/blog/reposicao-hidrica-no-cabelo/', destination: '/pt/blog/reposicao-hidrica-no-cabelo', permanent: true },
      { source: '/reconstrucao-do-fio', destination: '/pt/blog/reconstrucao-do-fio', permanent: true },
      { source: '/reconstrucao-do-fio/', destination: '/pt/blog/reconstrucao-do-fio', permanent: true },
      { source: '/blog/reconstrucao-do-fio', destination: '/pt/blog/reconstrucao-do-fio', permanent: true },
      { source: '/blog/reconstrucao-do-fio/', destination: '/pt/blog/reconstrucao-do-fio', permanent: true },
      { source: '/microagulhamento-capilar', destination: '/pt/blog/microagulhamento-capilar', permanent: true },
      { source: '/microagulhamento-capilar/', destination: '/pt/blog/microagulhamento-capilar', permanent: true },
      { source: '/blog/microagulhamento-capilar', destination: '/pt/blog/microagulhamento-capilar', permanent: true },
      { source: '/blog/microagulhamento-capilar/', destination: '/pt/blog/microagulhamento-capilar', permanent: true },
      { source: '/oleosidade-excessiva-do-couro-cabeludo-como-tratar', destination: '/pt/blog/oleosidade-excessiva-do-couro-cabeludo-como-tratar', permanent: true },
      { source: '/oleosidade-excessiva-do-couro-cabeludo-como-tratar/', destination: '/pt/blog/oleosidade-excessiva-do-couro-cabeludo-como-tratar', permanent: true },
      { source: '/blog/oleosidade-excessiva-do-couro-cabeludo-como-tratar', destination: '/pt/blog/oleosidade-excessiva-do-couro-cabeludo-como-tratar', permanent: true },
      { source: '/blog/oleosidade-excessiva-do-couro-cabeludo-como-tratar/', destination: '/pt/blog/oleosidade-excessiva-do-couro-cabeludo-como-tratar', permanent: true },
      { source: '/queda-capilar-dicas-para-resolver-ja', destination: '/pt/blog/queda-capilar-dicas-para-resolver-ja', permanent: true },
      { source: '/queda-capilar-dicas-para-resolver-ja/', destination: '/pt/blog/queda-capilar-dicas-para-resolver-ja', permanent: true },
      { source: '/blog/queda-capilar-dicas-para-resolver-ja', destination: '/pt/blog/queda-capilar-dicas-para-resolver-ja', permanent: true },
      { source: '/blog/queda-capilar-dicas-para-resolver-ja/', destination: '/pt/blog/queda-capilar-dicas-para-resolver-ja', permanent: true },
      { source: '/caspa-dicas-faceis-para-combater-agora', destination: '/pt/blog/caspa-dicas-faceis-para-combater-agora', permanent: true },
      { source: '/caspa-dicas-faceis-para-combater-agora/', destination: '/pt/blog/caspa-dicas-faceis-para-combater-agora', permanent: true },
      { source: '/blog/caspa-dicas-faceis-para-combater-agora', destination: '/pt/blog/caspa-dicas-faceis-para-combater-agora', permanent: true },
      { source: '/blog/caspa-dicas-faceis-para-combater-agora/', destination: '/pt/blog/caspa-dicas-faceis-para-combater-agora', permanent: true },
      { source: '/tratamento-de-mechas-que-transformam-seus-fios', destination: '/pt/blog/tratamento-de-mechas-que-transformam-seus-fios', permanent: true },
      { source: '/tratamento-de-mechas-que-transformam-seus-fios/', destination: '/pt/blog/tratamento-de-mechas-que-transformam-seus-fios', permanent: true },
      { source: '/blog/tratamento-de-mechas-que-transformam-seus-fios', destination: '/pt/blog/tratamento-de-mechas-que-transformam-seus-fios', permanent: true },
      { source: '/blog/tratamento-de-mechas-que-transformam-seus-fios/', destination: '/pt/blog/tratamento-de-mechas-que-transformam-seus-fios', permanent: true },
    ]
  },
}

export default nextConfig
